apiVersion: v1
kind: Service
metadata:
  name: gitrank-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: gitrank-backend
    component: gitrank-backend
    tier: backend
  clusterIP: None
