version: "3.9"

services:

  backend:
    build:
      context: ./backend
    command: gradle bootRun
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - app-tier
    depends_on:
      - db   
    restart: on-failure
    tty: true

  db:
    image: mysql
    container_name: db
    restart: on-failure
    ports:
      - 3307:3306
    volumes:
      - data_mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-tier
    tty: true
  
  scrapping:
    build:
      context: ./scrapping
    ports:
      - 5000:5000
    environment:
      FLASK_APP: ./app.py
      APP_NAME: scrapping
      FLASK_DEBUG: 1
    container_name: scrapping
    env_file: ./scrapping/.env
    restart: on-failure
    volumes:
      - ./scrapping:/scrapping/
    depends_on:
      - db
    networks:
      - app-tier
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  data_mysql: null
