apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitrank-redis
spec:
  selector:
    matchLabels:
      app: gitrank-redis
      component: gitrank-redis
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gitrank-redis
        component: gitrank-redis
        tier: backend
    spec:
      containers:
        - name: gitrank-redis
          image: redis:latest
          ports:
            - containerPort: 6379
