apiVersion: v1
kind: Service
metadata:
  name: gitrank-redis
spec:
  selector:
    app: gitrank-redis
    component: gitrank-redis
  ports:
  - name: gitrank-redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  clusterIP: None
