apiVersion: v1
kind: Service
metadata:
  name: gitrank-db
spec:
  ports:
    - name: gitrank-db
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: gitrank-db
    component: gitrank-db
  clusterIP: None
