apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker0
spec:
  selector:
    matchLabels:
      app: kafka
      id : "0"
  replicas: 2  
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://gitrank-kafka:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_CREATE_TOPICS
          value: go-kafka
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: gitrank-kafka
        - name: KAFKA_BROKER_ID
          value: "0"
