server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gitrank-db:3306/gitrank?serverTimezone=Asia/Seoul
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true

  cache:
    type: redis
    redis:
      time-to-live: 10800000
      cache-null-values: true

  redis:
    host: gitrank-redis
    port: 6379

  kafka:
    bootstrap-servers: gitrank-kafka:9092
    consumer:
      group-id: gitrank

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET}
            redirectUri: ${REDIRECT_URI}
            scope: repo, user
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 10000
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

blockchain:
  private-key: ${BLOCKCHAIN_PRIVATE_KEY}
  byte-code: ${BLOCKCHAIN_BYTE_CODE}
  password: ${BLOCKCHAIN_PASSWORD}
  wallet-key: ${BLOCKCHAIN_WALLET_KEY}
  contract-address: ${BLOCKCHAIN_CONTRACT_ADDRESS}

github:
  url: https://api.github.com/
  version-key: X-GitHub-Api-Version
  version-value: 2022-11-28

app:
  auth:
    token:
      auth-header: Authorization
      access-header: Access
      refresh-header: Refresh
      secret-key: ${JWT_SECRET_KEY}
      refresh-cookie-key: Refresh
  oauth2:
    authorizedRedirectUri: gitrank://github-auth

admin: ${ADMIN}
