server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api
spring:
  config:
    import:
      - classpath:env.yml
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true
  redis:
    host: localhost
    port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      group-id: gitrank
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: manual
    bootstrap-servers: localhost:9092
  sql:
    init:
      mode: never
