name: GitRank Android Dev Github Actions
on:
  push:
    paths:
      - '**.kt'
  pull_request:
    paths:
      - '**.kt'
defaults:
  run:
    shell: bash
    working-directory: ./android
jobs:
  android-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - run: chmod +x gradlew
    - run: ./gradlew build -x test
