name: GitRank iOS Dev Github Actions
on: [push, pull_request]
defaults:
  run:
    shell: bash
    working-directory: ./ios
jobs:
  ios-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: xcodebuild clean test -project ios.xcodeproj -scheme ios -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'
